version: "3.8"

services:
  web:
    build: .
    # remember that this is exposed on HOST as localhost:8008
    command: uvicorn src.python_server.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/src
    # HOST:CONTAINER
    ports:
      - "8008:8000"
